### ISSUE TITLE
joinAssays: Assay(s) has/have duplicated row names

### ISSUE THREAD

**Issue by cvanderaa** [rformassspectrometry/QFeatures#100]
I'm trying joining assays on a small  dataset but I bump into the error: 

```r
scp1 <- joinAssays(scp1, i = 4:6, name = "peptides")
```
```
harmonizing input:
  removing 54 sampleMap rows not in names(experiments)
  removing 16 colData rownames not in sampleMap 'primary'
Error in .unique_row_names(object) : 
  Assay(s) 7 has/have duplicated row names.
```

After digging into the code, I realized the error is linked to bad merging of the assay's `rowData`. Digging even further I realized this has to do with this check at [L12 in QFeatures-join.R](https://github.com/rformassspectrometry/QFeatures/blob/6d004fb9fcce3ee5d21028e324fbf7ec3630636b/R/QFeatures-join.R#L12)
```r
if (!isTRUE(all.equal(.x[[j]], .y[[j]])))
```
In my case, there is one variable `j` that causes the error:
```r
.x[[j]]
.y[[j]]
```
```
[1] 0 0 0 0 0 0
[1] -7.1054e-15  0.0000e+00 -1.4211e-14  0.0000e+00 -7.1054e-15  0.0000e+00
```
```r
all.equal(.x[[j]], .y[[j]])
```
```
TRUE
```
So, the issue is linked to the fact that `all.equal` omits floating-point approximations, but the `merge` method apparently does not. 

**Suggestion**: the variable `j` is the retention time calibration (specific to the assay) and it would be expected this variable is dropped out after merging. I think any variable with floating-point errors is specific to the assay it comes from and should be removed after merging. Hence, should we not replace `all.equal` by `identical`?

**Comment by lgatto** [comment]
Following up on a discussion with Chris and a debugging session, it transpired that in when running [`mergeSElist()`](https://github.com/rformassspectrometry/QFeatures/blob/6d004fb9fcce3ee5d21028e324fbf7ec3630636b/R/QFeatures-join.R#L52) on that test data, the joined assay (`joined_assay`) and rowdata (`joined_mcols`) have different rows:

```r
Browse[2]> nrow(joined_assay)
[1] 522
Browse[2]> nrow(joined_mcols)
[1] 530
```
because 
1. merging the assays rows is based on row names only
2. merging the row data also checks the variables/rownames and, as shown above, the `all.equal` identifies some values as identical, when they aren't, leading them to be kept as separate rows.

Afterwards, when a [new SE is created](https://github.com/rformassspectrometry/QFeatures/blob/6d004fb9fcce3ee5d21028e324fbf7ec3630636b/R/QFeatures-join.R#L59), the rownames are used to select the rows/features, which leads to some rows of the assay to be selected several times.  

After discussion, we concluded that the best was to switch to `identical()`, as suggested, as variables that aren't identical (even if equal) are PSM specific and don't need to be retained at the higher levels anyway. So best to get rid of these non-invariant variables to fix this issue.

Waiting for a PR.
