### ISSUE TITLE
Check fails on Bioconductor servers

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/QFeatures#125]
```
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  `actual`:   FALSE
  `expected`: TRUE 
  ── Failure (test_subsetByFeatures.R:41:5): subsetByFeatures ────────────────────
  `res1` not equal to `res2`.
  Attributes: < Component "drops": names for current but not for target >
  Attributes: < Component "drops": Length mismatch: comparison on first 0 components >
  ── Failure (test_subsetByFeatures.R:56:5): subsetByFeatures: full pipeline ─────
  `ftsub` not identical to fts["ProtA", ].
  Attributes: < Component "drops": names for current but not for target >
  Attributes: < Component "drops": Length mismatch: comparison on first 0 components >
  
  [ FAIL 8 | WARN 37 | SKIP 0 | PASS 351 ]
  Error: Test failures
  Execution halted
```
All details here:  http://bioconductor.org/checkResults/devel/bioc-LATEST/QFeatures/

**Comment by lgatto** [comment]
Ping @cvanderaa - could you have a look

**Comment by cvanderaa** [comment]
I'll have a look. I suspect this has to do with the recent changes in `MultiAssayExperiment`.

**Comment by cvanderaa** [comment]
So the issue is linked to updates in MAE. This means that as soon as we perform subsetting on the experiments, a warning is thrown: `'experiments' dropped; see 'metadata'` and the dropped experiments are listed in the metadata slot. I think this can lead to quite some confusion in our package to users as this could make them believe they are doing something wrong. Maybe we should catch the warning and hide it from the user where this warning is expected. 

There are quite some warnings and errors that come out because of that, so maybe we should think about this before adapting the tests?

These changes are probably an answer to those issues: https://github.com/waldronlab/MultiAssayExperiment/issues/290 and https://github.com/waldronlab/MultiAssayExperiment/issues/289. Maybe we should contribute to the discussion?

**Comment by lgatto** [comment]
I saw that Marcel committed a fix to this. `scp` should now depend on that specific version of `MultiAssayExperiment` by specifying the version in the Depends field.

**Comment by cvanderaa** [comment]
Yes but this partly solves the issue. The https://github.com/waldronlab/MultiAssayExperiment/commit/cc53db6e8db85fcf8ce47fabbd4d859ef1f949be commit only resolves the errors when all assays are subsetted from a `QFeatures` object. But warnings are still thrown when subsetting some of the assays, which occurs several times in the checks.

**Comment by cvanderaa** [comment]
Here are the remaining issues related to the changes in `MultiAssayExperiment`:

1. `test_Features.R`: we are checking the `QFeatures` subsetting method. `MAE` throws an error as soon as an assay is removed. I think we could simply catch the warning with no further change, what do you think?
2. `test_filerFeatures.R` and `test_subsetByFeatures`: assays that contain 0 features or 0 columns are no longer removed from the object when performing subsetting with `[`. Some tests in `test_filerFeatures.R` are expecting empty objects but this does no longer happen. **BUT** `subsetByFeatures` does remove empty assays. There is a **diverging** behavior between `[` and `subsetByFeatures`. What behavior should we keep for `QFeatures`? I would prefer the `[` behavior (with a `drop` argument) since this is in line with `MAE`. 
3. `test_join.R`: a warning is thrown because `joinAssays` performs an internal subsetting. This can be easily avoided with a little refactoring. 
4. `test_missing-data.R`: can be easily avoided with a little refactoring in test.

I'm currently preparing a PR to solve `3.` and `4.`, but @lgatto I would need your input on remarks `1.` and `2.`.
