### ISSUE TITLE
Function to extract all row data

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/QFeatures#86]
See `scp::rowDataToDF()`.

**Comment by cvanderaa** [comment]
The current `scp::rowDataToDF` function signature is:
- `object` A `QFeatures` object
- `i` A numeric() or character() vector indicating from which assays the `rowData` should be taken.
- `vars` A character() vector indicating which variables from the `rowData` should be extracted.

**To discuss**

1. I don't like the naming, since `rowData` should always return a `DataFrame`. What do you think about calling the function `collectRowData`, as it boils down to *picking* the `rowData` tables from different assays and put them in the same table (or *basket* if we stick to the gardening analogy :laughing:). An alternative would be `extractRowData`. 
2. **(edited)**: I'm wondering whether the `vars` is really needed, or at least we could implement that when missing, the function keeps all `rowData` variables *that are common to all selected assay*. 
3. Similarly, we could implement that the `rowData` of all assays are collected when `i` is missing.
4. Rename `vars` to: (1) `rowDataCols` for consistency with, *e.g.*, `MultiAssayExperiment::longFormat` or (2) `rowvars` for consistency with `selectRowData`.

@lgatto what do you think?

**Comment by lgatto** [comment]
I have seen your PR but haven't looked at it. 

My preference would be to use `rowData`, which is already known, and return a list of row data. However, the `...` in the signature is ignores, which means that the parameters you suggest can't be used. I don't think this is a problem because:
- The `i` you suggest isn't necessary, as it is possible to filter the `QFeatures` object to keep the assays of interest before extracting to row data list.
- The `vars` could be useful when you only want the same variables acorss all assays, but I don't think it is essential, as you mention.

If we have the same variable across all assays, then that list could be converted to a DataFrame with `do.call(rbind, x)`. If the variables are different, then `MsCoreUtils::rbindFill` should do the trick (not tested).

**Comment by cvanderaa** [comment]
This makes sense indeed. I'll adapt my PR.

**Comment by cvanderaa** [comment]
I think this issue can be closed unless you have additional suggestions?
